"""financeiro importacao legado 90

Revision ID: 5e3cdd212e76
Revises: d1f6b24c8e93
Create Date: 2026-09-26 22:55:21.370577
"""

import sqlalchemy as sa

from alembic import op

revision = "5e3cdd212e76"
down_revision = "d1f6b24c8e93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financeiro_importacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("nome_arquivo", sa.String(length=255), nullable=False),
        sa.Column("origem", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("export_path", sa.Text(), nullable=True),
        sa.Column("linhas", sa.Integer(), nullable=False),
        sa.Column("erros", sa.Integer(), nullable=False),
        sa.Column("avisos", sa.Integer(), nullable=False),
        sa.Column("ocorrencias", sa.JSON(), nullable=False),
        sa.Column("resumo", sa.JSON(), nullable=False),
        sa.Column("mensagem", sa.String(length=500), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_table(
        "financeiro_apropriacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("linha", sa.Integer(), nullable=False),
        sa.Column("empresa", sa.String(length=64), nullable=False),
        sa.Column("contraparte", sa.Text(), nullable=True),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("data_pagamento", sa.Date(), nullable=True),
        sa.Column("periodo", sa.Date(), nullable=True),
        sa.Column("data_inclusao_nf", sa.Date(), nullable=True),
        sa.Column("data_emissao", sa.Date(), nullable=True),
        sa.Column("valor_original", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("valor_incremento", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("valor_abatimento", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("valor_amortizado", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("valor_acrescimo", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("valor_deducao", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("valor_pago", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("valor_atual", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("local", sa.String(length=255), nullable=True),
        sa.Column("centro_custo", sa.String(length=255), nullable=True),
        sa.Column("id_natureza", sa.String(length=255), nullable=True),
        sa.Column("natureza_i", sa.String(length=32), nullable=True),
        sa.Column("natureza_ii", sa.String(length=32), nullable=True),
        sa.Column("natureza_iii", sa.String(length=32), nullable=True),
        sa.Column("natureza", sa.Text(), nullable=True),
        sa.Column("valor_apropriado", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("competencia", sa.Date(), nullable=True),
        sa.Column("classificacao", sa.String(length=100), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["financeiro_importacoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lote_id", "linha", name="uq_financeiro_lote_linha"),
    )
    op.create_index(
        op.f("ix_financeiro_apropriacoes_classificacao"),
        "financeiro_apropriacoes",
        ["classificacao"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financeiro_apropriacoes_competencia"),
        "financeiro_apropriacoes",
        ["competencia"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financeiro_apropriacoes_data_emissao"),
        "financeiro_apropriacoes",
        ["data_emissao"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financeiro_apropriacoes_empresa"),
        "financeiro_apropriacoes",
        ["empresa"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financeiro_apropriacoes_local"), "financeiro_apropriacoes", ["local"], unique=False
    )
    op.create_index(
        op.f("ix_financeiro_apropriacoes_lote_id"),
        "financeiro_apropriacoes",
        ["lote_id"],
        unique=False,
    )
    op.create_table(
        "financeiro_base_ativa",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["financeiro_importacoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(sa.table("financeiro_base_ativa", sa.column("id", sa.Integer())), [{"id": 1}])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("financeiro_base_ativa")
    op.drop_index(op.f("ix_financeiro_apropriacoes_lote_id"), table_name="financeiro_apropriacoes")
    op.drop_index(op.f("ix_financeiro_apropriacoes_local"), table_name="financeiro_apropriacoes")
    op.drop_index(op.f("ix_financeiro_apropriacoes_empresa"), table_name="financeiro_apropriacoes")
    op.drop_index(
        op.f("ix_financeiro_apropriacoes_data_emissao"), table_name="financeiro_apropriacoes"
    )
    op.drop_index(
        op.f("ix_financeiro_apropriacoes_competencia"), table_name="financeiro_apropriacoes"
    )
    op.drop_index(
        op.f("ix_financeiro_apropriacoes_classificacao"), table_name="financeiro_apropriacoes"
    )
    op.drop_table("financeiro_apropriacoes")
    op.drop_table("financeiro_importacoes")
    # ### end Alembic commands ###
